services:
  frontend:
    build:
      context: frontend
      target: dev-envs
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: backend
      target: dev-envs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - react-express
    expose: 
      - 3000
networks:
  react-express:
